# Generated by Django 5.0.6 on 2024-06-26 06:47

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='deadline',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
